# Generated by Django 5.0.3 on 2025-05-11 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0005_trainerservice_trainer_available_services'),
        ('trainings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledtraining',
            name='service_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to='gyms.trainerservice'),
            preserve_default=False,
        ),
    ]
