# Generated by Django 5.0.3 on 2025-05-24 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0002_scheduledtraining_service_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledtraining',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20),
        ),
    ]
