# Generated by Django 5.0.3 on 2025-06-02 21:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0008_remove_traineravailability_trainer_and_more'),
        ('trainings', '0003_alter_scheduledtraining_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='scheduledtraining',
            index=models.Index(fields=['user'], name='trainings_s_user_id_a8b1d3_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledtraining',
            index=models.Index(fields=['trainer'], name='trainings_s_trainer_b91764_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledtraining',
            index=models.Index(fields=['gym'], name='trainings_s_gym_id_b2b62c_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledtraining',
            index=models.Index(fields=['start_time'], name='trainings_s_start_t_fd51a2_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledtraining',
            index=models.Index(fields=['status'], name='trainings_s_status_663ee7_idx'),
        ),
    ]
