# Generated by Django 5.0.3 on 2025-03-28 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gym',
            old_name='image_url',
            new_name='photo_path',
        ),
    ]
