# Generated by Django 5.0.3 on 2025-04-20 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0003_alter_gym_photo_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gym',
            old_name='photo_path',
            new_name='photo',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='photo_path',
        ),
        migrations.AddField(
            model_name='trainer',
            name='photo',
            field=models.ImageField(blank=True, default='trainer-standard.png', upload_to=''),
        ),
    ]
