# Generated by Django 5.0.3 on 2025-05-11 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0004_rename_photo_path_gym_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainerService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
            ],
        ),
        migrations.AddField(
            model_name='trainer',
            name='available_services',
            field=models.ManyToManyField(related_name='trainers', to='gyms.trainerservice'),
        ),
    ]
