# Generated by Django 5.0.3 on 2025-05-27 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0005_trainerservice_trainer_available_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='description',
            field=models.TextField(blank=True, default='no description'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='bio',
            field=models.CharField(default='no bio', max_length=50),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='photo',
            field=models.ImageField(blank=True, default='trainer_blank_3-1.jpg', upload_to=''),
        ),
    ]
