# Generated by Django 5.0.3 on 2025-05-27 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0006_trainer_description_alter_trainer_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='bio',
            field=models.TextField(blank=True, default='no bio'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='description',
            field=models.TextField(blank=True, default='no description', max_length=50),
        ),
    ]
