# Generated by Django 5.0.3 on 2025-06-02 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0007_alter_trainer_bio_alter_trainer_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traineravailability',
            name='trainer',
        ),
        migrations.AddIndex(
            model_name='gym',
            index=models.Index(fields=['city'], name='gyms_gym_city_e7449d_idx'),
        ),
        migrations.AddIndex(
            model_name='gym',
            index=models.Index(fields=['name'], name='gyms_gym_name_ee4a7a_idx'),
        ),
        migrations.AddIndex(
            model_name='trainer',
            index=models.Index(fields=['gym'], name='gyms_traine_gym_id_c38401_idx'),
        ),
        migrations.AddIndex(
            model_name='trainerservice',
            index=models.Index(fields=['price'], name='gyms_traine_price_40e418_idx'),
        ),
        migrations.AddIndex(
            model_name='trainerservice',
            index=models.Index(fields=['name'], name='gyms_traine_name_6e95e1_idx'),
        ),
        migrations.DeleteModel(
            name='TrainerAvailability',
        ),
    ]
