# Generated by Django 5.0.3 on 2025-04-02 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0002_usermembership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershiptype',
            name='photo_path',
            field=models.ImageField(blank=True, default='mtype-standard.png', upload_to=''),
        ),
    ]
