# Generated by Django 5.0.3 on 2025-04-23 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0003_alter_membershiptype_photo_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membershiptype',
            old_name='photo_path',
            new_name='photo',
        ),
    ]
