# Generated by Django 5.0.3 on 2025-05-14 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0004_rename_photo_path_membershiptype_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershiptype',
            name='features_description',
            field=models.TextField(blank=True),
        ),
    ]
