# Generated by Django 5.0.3 on 2025-06-02 21:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0005_membershiptype_features_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='membershiptype',
            index=models.Index(fields=['price'], name='memberships_price_7d28e6_idx'),
        ),
        migrations.AddIndex(
            model_name='usermembership',
            index=models.Index(fields=['user'], name='memberships_user_id_07dfa1_idx'),
        ),
        migrations.AddIndex(
            model_name='usermembership',
            index=models.Index(fields=['is_active'], name='memberships_is_acti_79476e_idx'),
        ),
        migrations.AddIndex(
            model_name='usermembership',
            index=models.Index(fields=['start_date', 'end_date'], name='memberships_start_d_4467e4_idx'),
        ),
    ]
